import {useEffect,useState} from 'react';
import {api} from '@appdeploy/client';
type Summary={status:string;observed:number|null;active:number|null;checked_at:string;complete:boolean;message:string;categories:Record<string,number>;countries:Record<string,number>};
type Source={id:string;company_id:string;company:string;url:string;summary:Summary|null;stale:boolean};
type Job={job_key:string;title:string;location:string|null;country:string|null;category:string;source_url:string;posting_date:string|null;first_seen_at:string;last_seen_at:string;status:string};
type History={sources:Source[];jobs:Job[];next_page:number|null;observed_day:string;annual_unique_observed:number;annual_first_observed:number;monthly_first_observed:number;trend:{date:string;observed:number|null;confirmed_sources:number;categories:Record<string,number|null>}[]};
const fmt=(s:string)=>new Date(s).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'});
function CurrentStatus({jobKey,company}:{jobKey:string;company:string}){const[status,setStatus]=useState('');return <p><button onClick={()=>{api.get('/api/hiring-history?company='+encodeURIComponent(company)+'&job='+jobKey).then(r=>{const j=r.data.current_job;setStatus(j?(j.active?'直近記録：active（不在確認の猶予期間を含む）':'直近記録：inactive（一覧からの不在を確認）')+' · 最終観測 '+fmt(j.last_seen_at)+' JST':'記録未確認');}).catch(()=>setStatus('掲載状態を取得できませんでした。再試行してください。'));}}>最新の掲載状態を確認</button><span role='status'>{status}</span></p>;}
export default function HiringHistory({companyId}:{companyId?:string}){
  const[company,setCompany]=useState(companyId||'');const[date,setDate]=useState('');const[page,setPage]=useState(0);const[retry,setRetry]=useState(0);const[data,setData]=useState<History|null>(null);const[options,setOptions]=useState<Source[]>([]);const[error,setError]=useState('');
  const today=new Date(Date.now()+9*3600000).toISOString().slice(0,10);
  useEffect(()=>{let active=true;setData(null);setError('');const q=new URLSearchParams({page:String(page)});if(company)q.set('company',company);if(date)q.set('date',date);
    api.get('/api/hiring-history?'+q).then(r=>{if(!Array.isArray(r.data.sources)||!Array.isArray(r.data.jobs)||!Array.isArray(r.data.trend))throw Error('Invalid history');if(active){setData(r.data);if(!company)setOptions(r.data.sources);}}).catch(()=>{if(active)setError('求人履歴を取得できませんでした。下の採用情報は引き続き閲覧できます。');});return()=>{active=false};
  },[company,date,page,retry]);
  return <section className='story' aria-label='求人履歴'><h3>Hiring Intelligence · 求人履歴</h3><p>毎朝6:15 JSTに公開求人を確認します。初回収録は採用増加と区別し、未確認は0件に含めません。</p>
    <div className='filters'>{!companyId&&<label>履歴を見る会社<select value={company} onChange={e=>{setCompany(e.target.value);setPage(0)}}><option value=''>全社</option>{options.map(s=><option value={s.company_id} key={s.id}>{s.company}</option>)}</select></label>}<label>観測日（JST）<input type='date' value={date} max={today} onChange={e=>{setDate(e.target.value);setPage(0)}}/></label><button onClick={()=>{setDate('');setPage(0);setRetry(n=>n+1)}}>最新の履歴を再読込</button></div>
    {error&&<p role='alert'>{error}<button onClick={()=>setRetry(n=>n+1)}>再試行</button></p>}{!data&&!error&&<p role='status'>求人履歴を読み込み中…</p>}
    {data&&<><p className='meta'>観測日 {data.observed_day} · 当月初回観測 {data.monthly_first_observed}件 · 当年観測 {data.annual_unique_observed}件 / うち初回観測 {data.annual_first_observed}件（初回収録を含む）</p>
    {!data.sources.some(s=>s.summary)&&<p>まだ実行記録がありません。初回収集待ちです。求人なしを意味しません。</p>}
    <details open={!!company}><summary>会社別の観測件数・取得状況</summary><div className='source-status'>{data.sources.map(s=><article key={s.id}><a href={s.url} target='_blank' rel='noreferrer'>{s.company} ↗</a><p>{s.summary?.observed==null?'件数：未確認':`観測 ${s.summary.observed}件${s.summary.complete?'（一覧全件）':'（部分観測）'}`}{s.stale?' / 更新待ち':''}</p><p className='meta'>{s.summary?.message||'初回収集待ち'}{s.summary&&<> · {fmt(s.summary.checked_at)} JST</>}</p>{!company&&<button onClick={()=>{setCompany(s.company_id);setPage(0)}}>この会社の履歴</button>}</article>)}</div></details>
    {company&&<><h4>この日の観測求人</h4>{!data.jobs.length&&<p>表示できる観測求人はありません。取得状況を確認してください。</p>}{data.jobs.map(j=><article className='career-job' key={j.job_key}><h4><a href={j.source_url} target='_blank' rel='noreferrer'>{j.title} ↗</a></h4><p>{j.category} · {j.location||'勤務地未確認'} · {j.country||'国未確認'}</p><p className='meta'>掲載日 {j.posting_date||'未確認'}<br/>初回確認 {fmt(j.first_seen_at)} JST<br/>最終確認 {fmt(j.last_seen_at)} JST</p><CurrentStatus jobKey={j.job_key} company={company}/></article>)}<div className='range-buttons'>{page>0&&<button onClick={()=>setPage(p=>p-1)}>前の25件</button>}{data.next_page!==null&&<button onClick={()=>setPage(data.next_page!)}>次の25件</button>}</div></>}
    <details><summary>日別・重要職種の求人推移</summary><p className='meta'>観測できた情報源の合計です。取得対象が増減した日は単純比較できません。</p><div style={{overflowX:'auto'}}><table><thead><tr>{['日付','観測求人','確認ソース','Engineering','Maintenance','Project / CapEx','Production','Milling'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.trend.slice(-90).map(t=><tr key={t.date}><td>{t.date}</td><td>{t.observed??'未確認'}</td><td>{t.confirmed_sources}</td>{['Engineering','Maintenance','Project / CapEx','Production / Operations','Milling'].map(c=><td key={c}>{t.categories[c]??'未確認'}</td>)}</tr>)}</tbody></table></div></details>
    <details><summary>集計・掲載終了の判定方法</summary><p>件数は観測した固有求人の数で、採用人数ではありません。掲載日と初回確認日は別々に保存します。初回収録以前の求人履歴は復元していません。</p><p>完全な求人一覧で別々の3日間・48時間以上不在を確認した求人をinactiveにします。取得失敗・部分観測では終了判定しません。過去日の一覧は、その日に観測した状態です。</p><p>求人増加と設備投資の関係は今後検証する仮説です。因果関係は断定しません。</p></details></>}
  </section>;
}

