import routes from './seoCatalog.json';
import navItems from './navigationCatalog.json';
const regionAliases:Record<string,string>={japan:'companies/japan',us:'companies/us',europe:'companies/europe',australia:'companies/australia',canada:'companies/canada',china:'companies/china'};
const canonicalPaths=new Set(routes.map(item=>item.path));
const navigationOrder=['home','companies','mills','compare','career','machines','tech','archive','method','contact'];const navigationLabels:Record<string,string>={home:'ニュース',companies:'企業を探す',mills:'工場を探す',compare:'会社を比較',career:'採用情報',machines:'製粉機械',tech:'製粉技術',archive:'過去記事',method:'評価基準',contact:'お問い合わせ'};export const mainNavigation=[...navItems].sort((a,b)=>navigationOrder.indexOf(a.route)-navigationOrder.indexOf(b.route)).map(item=>[item.route,navigationLabels[item.route]||item.label] as const);
function normalizeTarget(target:string){const raw=target.replace(/^#/,'').replace(/^\/+/, '').replace(/\/+$/,'');if(!raw||raw==='home')return '/';const url=new URL('/'+raw,location.origin);const path=url.pathname.replace(/\/+$/,'')||'/';return path+url.search}
export function appHref(target:string){const next=normalizeTarget(target);const url=new URL(next,location.origin);const current=(location.pathname.replace(/\/+$/,'')||'/').split('/').filter(Boolean);const ups='../'.repeat(Math.max(0,current.length-1));if(url.pathname==='/')return ups||'./';return ups+url.pathname.slice(1)+url.search}
export function routeFromLocation(){const path=location.pathname.replace(/^\/+|\/+$/g,'');return path||'home'}
export function isAppPath(pathname:string){return canonicalPaths.has(pathname.replace(/\/+$/,'')||'/')}
export function navigateApp(target:string,replace=false){const next=normalizeTarget(target);if(location.pathname+location.search===next&&!location.hash)return;history[replace?'replaceState':'pushState']({},'',next);window.dispatchEvent(new PopStateEvent('popstate'))}
export function prepareInitialRoute(){const params=new URLSearchParams(location.search);const handoff=params.get('__route');if(handoff){const restored=new URL(handoff,location.origin);history.replaceState({},'',(restored.pathname.replace(/\/+$/,'')||'/')+restored.search+restored.hash)}if(location.hash){let raw=location.hash.slice(1).replace(/^\/+/, '');try{raw=decodeURIComponent(raw)}catch{}const target=raw==='ratings'?'companies':regionAliases[raw]||(/^mills-/.test(raw)?'mills/'+raw.slice(6):raw);history.replaceState({},'',normalizeTarget(target))}const clean=location.pathname.replace(/\/+$/,'')||'/';if(clean!==location.pathname)history.replaceState({},'',clean+location.search)}

